name: highlight.exe ci

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: buildjet/cache@v3
      with:
        path: node_modules
        key: npm-${{ hashFiles('**/package.json') }}
    - uses: oven-sh/setup-bun@v1
    - run: bun install
    - run: make build
    - name: "Generate tag"
      run: echo "tag_name=$(./highlight.exe --version)" >> $GITHUB_ENV
    - run: gzip highlight.exe
    - name: Publish release
      uses: softprops/action-gh-release@v1
      with:
        files: highlight.exe.gz
        tag_name: ${{ env.tag_name }}
