name: highlight.exe ci

on:
  push:
    tags: ["*"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: buildjet/cache@v3
      with:
        path: node_modules
        key: npm-${{ hashFiles('**/package.json') }}
    - uses: oven-sh/setup-bun@v1
    - run: bun install
    - run: make gzip
    - name: Publish release
      uses: softprops/action-gh-release@v1
      with:
        files: highlight.exe.gz
